name: calpin
description: Une simple aplication dénommée &#x27;calpin&#x27;. On sait tous ce qu&#x27;est un calpin.Il permet d&#x27;enregistrer des notes et des taches, voir des rdv; et pourquoi pas des idées ?

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  path_provider: ^1.4.0
  sqflite: ^1.1.7+1
  flutter_slidable: ^0.5.4
  intl: ^0.15.0
  intl_phone_number_input: ^0.1.0
  flutter_calendar_carousel: ^1.4.2
  image_picker: ^0.6.1+8
  flutter_rounded_date_picker: ^0.2.3
  shifting_tabbar: ^0.3.1
  rflutter_alert: ^1.0.3
  flushbar: ^1.9.1
  flutter_typeahead: ^1.7.0
  circular_check_box: ^1.0.1
  card_settings: ^1.4.2
#/home/mesabo/development/flutter/.pub-cache/hosted/pub.dartlang.org/card_settings-1.4.2/lib/widgets/text_fields/card_settings_email.dart
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Mali
      fonts:
        - asset: assets/fonts/Mali/MaliBold700.ttf
          weight: 700
        - asset: assets/fonts/Mali/MaliLight300.ttf
          weight: 300
        - asset: assets/fonts/Mali/MaliMedium500.ttf
          weight: 500
        - asset: assets/fonts/Mali/MaliRegular400.ttf
          weight: 400

        - asset: assets/fonts/Mali/MaliItalic400.ttf
          style: italic

  #     - family: Trajan Pro
  #       fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
